### ISSUE TITLE
step cargo run --bin playpen fails

### ISSUE THREAD

**Issue by salmonix** [rust-lang/rust-playpen#256]
Hi there! I am trying to build playpen locally. At step cargo run --bin playpen fails I receive the following error:

```
Compiling router v0.1.1
Compiling staticfile v0.2.0
Compiling rust-playpen v0.1.0 (file:///home/lforro/rust-playpen)
 Finished debug [unoptimized + debuginfo] target(s) in 60.33 secs
 Running `target/debug/playpen`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', ../src/libcore/result.rs:788
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Backtrace says:
```
export RUST_BACKTRACE=1 && cargo run --bin playpen
    Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/playpen`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', ../src/libcore/result.rs:788
stack backtrace:
   1:     0x55c88fa0f3f9 - std::sys::backtrace::tracing::imp::write::h00e948915d1e4c72
   2:     0x55c88fa156cc - std::panicking::default_hook::_{{closure}}::h7b8a142818383fb8
   3:     0x55c88fa14919 - std::panicking::default_hook::h41cf296f654245d7
   4:     0x55c88fa15008 - std::panicking::rust_panic_with_hook::h4cbd7ca63ce1aee9
   5:     0x55c88fa14e62 - std::panicking::begin_panic::h93672d0313d5e8e9
   6:     0x55c88fa14dd0 - std::panicking::begin_panic_fmt::hd0daa02942245d81
   7:     0x55c88fa14d51 - rust_begin_unwind
   8:     0x55c88fa4f83f - core::panicking::panic_fmt::hbfc935564d134c1b
   9:     0x55c88f6debfc - core::result::unwrap_failed::h5143d39947ff2959
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libcore/result.rs:29
  10:     0x55c88f6c724b - _<core..result..Result<T, E>>::unwrap::h9671ae71bc60a491
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libcore/result.rs:726
  11:     0x55c88f72ff4d - playpen::main::h9a1ec7a47358bec6
                        at /home/lforro/rust-playpen/src/bin/playpen.rs:288
  12:     0x55c88fa1d1b6 - __rust_maybe_catch_panic
  13:     0x55c88fa14092 - std::rt::lang_start::h53bf99b0829cc03c
  14:     0x55c88f738163 - main
  15:     0x7f3ef6e9782f - __libc_start_main
  16:     0x55c88f681ea8 - _start
  17:                0x0 - <unknown>
```

rustc: rustc 1.12.0 (3191fbae9 2016-09-23
cargo 0.13.0-nightly (109cb7c 2016-08-19)

Bests,
salmonix

**Comment by TimNN** [comment]
The failing line seems to be

```rust
Command::new("pygmentize").spawn().unwrap().kill().unwrap();
```

which probably means that `pygments` is not installed (`[sudo] pip install pygments`).

This could probably use a better error message and should be added to the install instructions.

**Comment by hoangtranwork** [comment]
It actually the pyments installation that fix this. +1 for adding `pip install pygments` to `System Requirements`
